### ISSUE TITLE
Potential App Switching Conflict

### ISSUE THREAD

**Issue by rbreaves** [Jonchun/ubuntu2macOS#1]
```
Switch Windows → Ctrl+Tab (cmd+tab) 
```

Just something to note, a number of browsers and text editors will use Ctrl+Tab to switch tabs within the app itself, which is one of the main reasons Kinto does not even offer to set that hotkey for the end users. It would be more mac like, but it could also prevent normal functionality.

I am working that issue out on the dev branch of Kinto and it does work pretty well under Gnome and xfce, but not under KDE due to it not behaving very well with the xkb remapping of the keys. 

You can actually checkout and install the dev branch right now if you want and the Cmd+Tab will work without you remapping the window switcher to Ctrl+Tab.

The app switcher just doesn't want to work well under KDE when the Alt or Ctrl key is being remapped - it ignores the key being held down essentially. I might be able to fix it once I implement a udev/hwdb keyswap in addition to xkb - but for now it is what it is.

For a more detailed answer for how dev works in kinto on the app switching this is the chunk of code that maps it.. but there is also a remap that happens in the Gnome preferences that sets it to use the F13 and F14 keys for going forwards and backwards since those typically go unused.

// App Switching
(Cmd position) Ctrl+Tab = Ctrl+F14
(Cmd position) Ctrl+Shift+Tab = Ctrl+F13

// In App Tab Switching
(Ctrl position) Super+Tab = Ctrl+Tab
(Ctrl position) Super+Shift+Tab = Ctrl+Shift+Tab

This is pretty much the only way I could devise it so that no loss in functionality occurs. I would have this merged into master - but until I find a similar answer for KDE I do not want to merge it, because every other feature I have in master works across Gnome, KDE and xfce equally.

```
partial xkb_symbols "mac_appcycle" {
    // Cycle App and In App Tab Switching
    key <FK13> { [ F13 ] };
    key <FK14> { [ F14 ] };
    replace key <TAB> {
        type[Group1]= "ONE_LEVEL_CMD",
        symbols[Group1]= [
            Tab,
            Tab,
            F14,
            F13,
            NoSymbol,
            NoSymbol
        ],
        actions[Group1]= [
            // Base
            NoAction(),
            // Shift
            NoAction(),
            // Control
            Redirect(key=<FK14>),
            // Control + Shift
            Redirect(key=<FK13>),
            // Super
            Redirect(key=<TAB>,mods=Control,clearmods=Mod4+Super),
            // Super + Shift
            Redirect(key=<TAB>,mods=Control,clearmods=Mod4+Super)
        ]
    };
};
```

**Comment by rbreaves** [comment]
I also have a few users that report slowness with their Alt+Tab switching under Kinto master, but it's not something I have really been able to reproduce - if I can then only slightly, half a second to a full second and it is not consistent. I am using a VM though, no idea if that impacts things or not.

**Comment by jonchun** [comment]
This is incredible! Thanks! I'll check out the dev branch now. The way you have it (ctrl position+tab) is exactly what I would have requested/recommended as well for in-app switching, with cmd+tab for window switching.

For what it's worth, I'm on baremetal on 2 machines and haven't noticed any slowness on cmd-tab switching.

**Comment by rbreaves** [comment]
Thank you for letting me know, that does make me feel a little better to know that just because I am not experiencing it, Alt+Tab slowness, in my VM or my 2 chromebooks running galliumOS (xfce), so it is good to know that your bare metal Ubuntu install is app switching at normal speed.

I imagine my repo is under enough use where if it was a more common or a widespread issue I'd probably have more than 3 users mentioning it, but hopefully someone will notice what the issue is at some point. One of the 3 mentioned having been on a fresh install - but there's got to be some additional software or maybe even a hardware/keyboard problem that needs addressing.

**Comment by jonchun** [comment]
This is being worked on in kinto so closing.
